#include "PAL/WinTextureHandle.h"

#ifdef BRWL_PLATFORM_WINDOWS

BRWL_RENDERER_NS


namespace PAL
{
#define HANDLE_TYPE_ WinTextureHandle
	FOR_EACH_WIN_TEXTURE_HANDLE_METHOD(TEXTURE_HANDLE_METHOD_IMPL)
#undef HANDLE_TYPE_
}

BRWL_RENDERER_NS_END

#endif // BRWL_PLATFORM_WINDOWS

