# This is a basic workflow to help you get started with Actions

name: Generate File Headers
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:  push
jobs:
  autogen:
    name: Autogen
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    #- name: Install dependencies
    #  run: python -m pip install --upgrade pip setuptools wheel
    - name: Run autogen
      run: |
        python ./tools/autogen.py
    - name: Commit
      run: |
        git config --global user.name 'Bot'
        git config --global user.email 'bruluk5w@users.noreply.github.com'
        git diff-index --quiet HEAD || git commit -am "File Headers"
        git push


