# This is a basic workflow to help you get started with Actions

name: Generate File Headers
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:  push
jobs:
  generate_file_headers:
    name: Generate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/replace-tokens@v1
        with:
          #tokenPrefix: '#prag'
          #tokenSuffix: ' once'
          files: '["**/test.h"]' #'["**/*.h"]'
        env:
          BLA: '(c) 2020 - Lukas Brunner\\n\\r'
      - name: Commit Changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "File Headers"
          git push
      

